#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-jQuery
Version  : 1.10.2.1
Release  : 9
URL      : https://pypi.python.org/packages/source/X/XStatic-jQuery/XStatic-jQuery-1.10.2.1.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-jQuery/XStatic-jQuery-1.10.2.1.tar.gz
Summary  : jQuery 1.10.2 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-jQuery-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-jQuery
--------------
jQuery javascript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-jQuery package.
Group: Default

%description python
python components for the XStatic-jQuery package.


%prep
%setup -q -n XStatic-jQuery-1.10.2.1

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
